const ROLES = {
  ADMIN: 'ADMIN',
  VENDOR: 'VENDOR',
  DEPOT_OFFICER: 'DEPOT_OFFICER',
  INSPECTOR: 'INSPECTOR',
  ZONAL_MANAGER: 'ZONAL_MANAGER',
};

const PERMISSIONS = {
  CREATE_QR: 'CREATE_QR',
  VIEW_QR: 'VIEW_QR',
  UPDATE_QR: 'UPDATE_QR',
  DELETE_QR: 'DELETE_QR',
  MANAGE_VENDORS: 'MANAGE_VENDORS',
  CONDUCT_INSPECTION: 'CONDUCT_INSPECTION',
  VIEW_REPORTS: 'VIEW_REPORTS',
  MANAGE_USERS: 'MANAGE_USERS',
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',
  EXPORT_DATA: 'EXPORT_DATA',
};

const ROLE_PERMISSIONS = {
  [ROLES.ADMIN]: Object.values(PERMISSIONS),
  [ROLES.VENDOR]: [
    PERMISSIONS.VIEW_QR,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [ROLES.DEPOT_OFFICER]: [
    PERMISSIONS.CREATE_QR,
    PERMISSIONS.VIEW_QR,
    PERMISSIONS.UPDATE_QR,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.EXPORT_DATA,
  ],
  [ROLES.INSPECTOR]: [
    PERMISSIONS.VIEW_QR,
    PERMISSIONS.CONDUCT_INSPECTION,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_DASHBOARD,
  ],
  [ROLES.ZONAL_MANAGER]: [
    PERMISSIONS.VIEW_QR,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.VIEW_DASHBOARD,
    PERMISSIONS.EXPORT_DATA,
    PERMISSIONS.MANAGE_VENDORS,
  ],
};

const FITTING_TYPES = {
  ERC: 'Elastic Rail Clip',
  PANDROL: 'Pandrol Clip',
  SLEEPER: 'Concrete Sleeper',
  FASTENER: 'Rail Fastener',
  BOLT: 'Track Bolt',
  PLATE: 'Base Plate',
};

const INSPECTION_STATUS = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
};

const FITTING_STATUS = {
  MANUFACTURED: 'MANUFACTURED',
  IN_TRANSIT: 'IN_TRANSIT',
  INSTALLED: 'INSTALLED',
  UNDER_INSPECTION: 'UNDER_INSPECTION',
  OPERATIONAL: 'OPERATIONAL',
  DEFECTIVE: 'DEFECTIVE',
  RECALLED: 'RECALLED',
  DECOMMISSIONED: 'DECOMMISSIONED',
};

const AI_PREDICTION_STATUS = {
  LOW_RISK: 'LOW_RISK',
  MEDIUM_RISK: 'MEDIUM_RISK',
  HIGH_RISK: 'HIGH_RISK',
  CRITICAL: 'CRITICAL',
};

const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
};

const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  AUTHORIZATION_ERROR: 'AUTHORIZATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  DUPLICATE_ENTRY: 'DUPLICATE_ENTRY',
  DATABASE_ERROR: 'DATABASE_ERROR',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
};

const CACHE_KEYS = {
  DASHBOARD_STATS: 'dashboard:stats',
  VENDOR_RANKING: 'vendor:ranking',
  FAILURE_RATE: 'failure:rate',
  WARRANTY_ALERTS: 'warranty:alerts',
};

module.exports = {
  ROLES,
  PERMISSIONS,
  ROLE_PERMISSIONS,
  FITTING_TYPES,
  INSPECTION_STATUS,
  FITTING_STATUS,
  AI_PREDICTION_STATUS,
  HTTP_STATUS,
  ERROR_CODES,
  CACHE_KEYS,
};
